source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

use_frameworks!

target 'SupportingPayPalPayments' do
	
	pod 'AirServiceKit', :git => 'https://github.com/airservice/Open-API-and-SDKs.git'
	pod 'ASPayPalPayments', :git => 'https://github.com/airservice/Open-API-and-SDKs.git'	
end
